name: Build CASS rules

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (PyMuPDF + PyYAML)
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary=:all: "pymupdf==1.24.9" pyyaml
          python -c "import fitz,sys; print('PyMuPDF OK', fitz.__doc__.splitlines()[0], file=sys.stderr)"

      - name: Generate docs/data/rules.yaml
        run: |
          python scripts/extract_rules_from_pdf.py data/source_pdfs/*.pdf --out docs/data/rules.yaml
          ls -la docs/data || true
          head -n 30 docs/data/rules.yaml || true

      - name: Commit rules.yaml (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/rules.yaml
          git commit -m "chore: regenerate rules.yaml" || echo "No changes to commit"
          git push
